@url = https://localhost:7189
@email = user1@deepfocus.io
@password = secret
@role = user
@accessToken = secret
###
GET {{url}}

###
GET {{url}}/account
Authorization: Bearer {{accessToken}}

###
POST {{url}}/account/sign-up
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}",
  "role": "{{role}}"
}

###
POST {{url}}/account/sign-in
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

###
DELETE {{url}}/account/sign-out
Content-Type: application/json

{

}